### PR TITLE
Adjust dump method in Extended\ACF\Fields\Field to utilize object cloning

### LINKED ISSUE #153: Calling ->dump() on a field with sub_fields always returns error
### Description of the bug
Using ->dump() on a Field that has `sub_fields` always return the following error:
```
Fatal error: Uncaught Error: Call to a member function get() on array
```
The dump itself is returned but the error happens afterwards.

Screenshot 2024-08-16 at 14 30 56

Dumps on other fields are returned without any errors. Also tested on the Repeater field with the same resulting error as above.

### Steps to reproduce
```php
register_extended_field_group([
	'title' => 'Kundeninformationen',
	'fields' => [
		Image::make('Logo'),
		Text::make('Firmenname'),
		Text::make('Strasse/Nr.'),
		Text::make('PLZ'),
		Text::make('Ort'),
		Text::make('Telefon'),
		Group::make('Social Media')
			->fields([
				URL::make('Facebook'),
				URL::make('Instagram'),
				URL::make('LinkedIn'),
				URL::make('X'),
				URL::make('YouTube'),
			])->dump(),
	],
	'location' => [Location::where('post_type', 'page')],
]);
```

### PR DESCRIPTION
**Pull request by marcoluzi**
_This PR will fix #153._ 

### Description
This pull request refactors the get method in the Extended\ACF\Fields\Field class to utilize PHP object cloning. The changes ensure that field instances, particularly those with sub_fields, layouts, and conditional_logic, are processed independently, preventing unintended modifications to the original objects during method execution.

### Changes Made
- Object Cloning: Implemented object cloning in the get method to create independent instances of sub_fields, layouts, and conditional_logic before processing.
- Safety Checks: Added conditional checks to ensure clone is only applied to objects, safeguarding against potential errors when dealing with non-object types.

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request. This approach may not work as we create field keys on the fly. If the keys are generated without a parent, they could become invalid. Is there a way to clone the field within the `dump` method instead?

**Comment by marcoluzi** [comment]
That would only be symptom control. I actually stumbeled across this bug when I was trying to use the get method itself. So if we would adjust the dump() method, the problem would still occure if someone would use the get() method.

Here is a code snippet of how I want to utilize the get() method:

```php
private function registerOptionPageContext(array $option_page): void
{
	if (!isset($option_page['page_settings']['timber_context_key'])) {
		return;
	}

	add_filter('timber/context', function ($context) use ($option_page) {
		$context[$option_page['page_settings']['timber_context_key']] = $this->getFieldsContext($option_page);
		return $context;
	});
}
private function getFieldsContext(array $option_page): array
{
	$fieldsContext = [];
	$fields = $option_page['acf_settings']['fields'] ?? [];

	foreach ($fields as $field) {
		$key = $field->get()['key'];
		$name = $field->get()['name'];
		$fieldsContext[$name] = get_field($key, 'option');
	}

	return $fieldsContext;
}
```

With those two methods I am looping through all the fields registered in option pages and and adding them to the timber contect, to make them available in the frontend. I am using the get() method to get the field key, so i can use the get_field() function. This all needs to work dynamically since extended-acf generates the keys on the fly.

**Comment by marcoluzi** [comment]
That's a very good question. I've never questioned this, since it has always been like this in the theme since I work here. I checked the Timber Docs and they recommend to use `get_fields('options');` to get all values registered on option pages. This works for me. Thanks for the hint. Using this, my usecase of extended-acf is working now.

As for this PR: I think it would still be better to find a solution for fields that utilize child fields. As of now, even if you don't use the get() method, as you suggested, the dump() method is broken for fields with subfields. So I would either prevent the usage of dump() on those fields or maybe trying to find a solution for this.

I'm not that familiar with the codebase of this repo or the acf source code. But could something like this be a solution?
```php
/** @internal */
public function get(string|null $parentKey = null): array
{
    // Resolve the parent key to ensure it's valid within the current context
    $resolvedParentKey = $parentKey !== null ? Key::resolveParentKey($parentKey, $this->settings['name']) : null;

    $key =
        $this->settings['key'] ??
        ($resolvedParentKey !== null ? $resolvedParentKey . '_' : '') . Key::sanitize($this->settings['name']);

    if ($this->type !== null) {
        $this->settings['type'] = $this->type;
    }

    if (isset($this->settings['conditional_logic'])) {
        $this->settings['conditional_logic'] = array_map(
            fn($rules) => is_object($rules) && method_exists($rules, 'get')
                ? $rules->get($resolvedParentKey)
                : $rules,
            $this->settings['conditional_logic'],
        );
    }

    if (isset($this->settings['layouts'])) {
        $this->settings['layouts'] = array_map(
            fn($layout) => is_object($layout) && method_exists($layout, 'get')
                ? $layout->get($key)
                : $layout,
            $this->settings['layouts'],
        );
    }

    if (isset($this->settings['sub_fields'])) {
        $this->settings['sub_fields'] = array_map(
            fn($field) => is_object($field) && method_exists($field, 'get')
                ? $field->get($key)
                : $field,
            $this->settings['sub_fields'],
        );
    }

    if (isset($this->settings['collapsed'], $this->settings['sub_fields'])) {
        foreach ($this->settings['sub_fields'] as $field) {
            if (is_array($field) && isset($field['name']) && $field['name'] === $this->settings['collapsed']) {
                $this->settings['collapsed'] = $field['key'] ?? $this->settings['collapsed'];
                break;
            }
        }
    }

    $this->settings['key'] ??= Key::generate($key, $this->keyPrefix);

    return $this->settings;
}
```

**Comment by vinkla** [comment]
Thank you for the update. Have you tried this approach? The error still seems to be occurring on my end.

**Comment by vinkla** [comment]
Thank you for the update. Have you tried this approach? The error still seems to be occurring on my end.

**Comment by marcoluzi** [comment]
@vinkla It does work on my end. 🤔

**Comment by vinkla** [comment]
I know why I still see the error on my side. It's because I have nested repeaters. We might need to map over the fields first and clone them if they have subfields.

**Comment by marcoluzi** [comment]
Do you need me to do anything else?

**Comment by vinkla** [comment]
Sorry for the delay, haven't had time to look into this. Will look at it in the future.

File: src/Fields/Field.php [hunk 1]
```diff
@@ -142,4 +145,21 @@ public function get(string|null $parentKey = null): array
 
         return $this->settings;
     }
+
+    /**
+     * Deep clone the current object and all nested fields.
+     */
+    protected function deepClone(): static
```
Comment (vinkla) [inline src/Fields/Field.php:152]:
```suggestion
    private function cloneWithNestedFields(): static
```

File: src/Fields/Field.php [hunk 2]
```diff
@@ -142,4 +145,21 @@ public function get(string|null $parentKey = null): array
...
+    {
+        $clone = clone $this;
+
+        if (isset($this->settings['sub_fields'])) {
+            $clone->settings['sub_fields'] = array_map(
+                fn($field) => $field->deepClone(),
```
Comment (vinkla) [inline src/Fields/Field.php:158]:
```suggestion
                fn(Field $field) => $field->cloneWithNestedFields(),
```

File: src/Fields/Field.php [hunk 3]
```diff
@@ -62,7 +62,10 @@ public function withSettings(array $settings): static
 
     public function dump(...$args): static
     {
-        dump($this->get(), ...$args);
+        $clone = $this->deepClone();
+        $settings = $clone->get();
```
Comment (vinkla) [inline src/Fields/Field.php:66]:
```suggestion
        $settings = $this->cloneWithNestedFields()->get();
```

File: src/Fields/Field.php [hunk 4]
```diff
@@ -142,4 +145,21 @@ public function get(string|null $parentKey = null): array
 
         return $this->settings;
     }
+
+    /**
+     * Deep clone the current object and all nested fields.
+     */
+    protected function deepClone(): static
+    {
```
Comment (vinkla) [inline src/Fields/Field.php:153]:
```suggestion
    private function cloneRecursively(): static
    {
```

File: src/Fields/Field.php [hunk 5]
```diff
@@ -142,4 +144,18 @@ public function get(string|null $parentKey = null): array
 
         return $this->settings;
     }
+
+    private function cloneRecursively(): static
```
Comment (vinkla) [inline src/Fields/Field.php:148]:
```suggestion
    /** @internal */
    private function cloneRecursively(): static
```

**Comment by vinkla** [comment]
Thank you Marco! Better late than never 😉

**Comment by marcoluzi** [comment]
@vinkla I'm glad to hear that. 🥳
